### ISSUE TITLE
Switch to polling for LND RPC

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#108]
For the entire existence of LND PeerSwap we wasted a lot of cycles while attempting to debug stuff only to find we were experiencing intermittent unrelated failures where grpc is yet again flaky. It is supposed to recover on its own but it doesn't. We could try to somehow fix grpc connection recovery but I think it isn't worth it because there is no solution to #57 where the underlying restarted LND had forgotten subscriptions. We also heard from another major app that they always poll LND with new connections and that had been reliable for them.

"Switch to polling" is the general idea but this adds new complications.

* If every RPC is a new connection then you need to recheck each time if LND is synced. Maybe that's fast enough so it's OK for now? Let's find out.
* But some things we were relying upon are not a simple query but rather subscriptions.
* Maybe both of the above would be helped by making LND RPC calls **indirect** via an event queue. The event queue is another thread acting as a RPC proxy where only it interfaces with LND RPC. It monitors for temporary LND errors or a LND restart. In those cases it either blocks to wait for possible recovery, or passes the raw error messages to the calling function. The event queue could also implement a "subscription" model that is remembered only internally within PeerSwap runtime memory but it actually uses polling to check if the subscribed event had happened.

I don't know what approach would be easiest to implement. Slow and simple might be good enough for now. The event queue might be more efficient in the long-term but adds complexity that might not be worth it.

I wonder if all those extra polling connections and frequent "are you ready?" calls would spam up LND's logs?

**Comment by wtogami** [comment]
If we find polling is too difficult to quickly implement, we should implement a stop-gap.

> If LND RPC fails in a way that isn't recoverable, log the failure and exit PeerSwap. The state machine should be able to handle recovery at any point right? Then the sysadmin is expected to have `peerswapd` automatically restart upon exit via systemd service or something.

We need either 100% polling or this exit upon error behavior for the v0.3 release.

**Comment by kornpow** [comment]
I think the method of exitting peerswap if LND rpc calls fail is the way to go, and trying to recover all of the connections/swaps on startup. This way the existing code can work.

Maybe we also have some kind of polling loop to detect when LND is down, maybe that is something that is already occurring with the subscriptions.

I also don't think you need to overthink this and query `GetInfo` before every single API call.
We could subscribe/poll to the WalletState
https://api.lightning.community/#service-state
At least this tells us if the wallet is unlocked.

LNDs logs are already pretty full, I wouldn't worry about it, in my experience the logs are filled mostly with internals, not rpc info. And the logs are configurable by subsystem if people didn't want something.

**Comment by wtogami** [comment]
> Maybe we also have some kind of polling loop to detect when LND is down, maybe that is something that is already occurring with the subscriptions.

I like this. It would be a simple PeerSwap-internal health monitor to query before doing RPC calls.

**Comment by nepet** [comment]
We have to distinguish between two different cases AFAICT right now:
- __Requests__: Single requests to the lnd grpc server
- __Streams__: "Persistent" requests/response streams that we use for notifications

The problem we want to tackle: Connection loss to the lnd grpc server. I have the following suggestions:

- __Requests__:
The RPC connection is automatically being handled by grpcs `clientconn.go` and reconnects. See https://github.com/grpc/grpc-go/blob/64174955202ffb5ea4122e25d1aaece49cc5a3ed/clientconn.go#L993-L1000.
However if the source of an error of a request is a broken connection -> We might want to `waitUntilConnectionIsReady` and subsequently try to perform the request. `waitUntilConnectionIsReady` might also include a check on ln sync and wallet state. `waitUntilConnectionIsReady` can have a timeout on which we exit `peerswaplnd` and rely on the user/admin to restart `peerswaplnd`.

- __Streams__:
At some points we subscribe to streams e.g. at the transaction watcher. Here we have two possibilities:
  - a) Do not use streams and poll every `x` seconds using the same strategy as above.
  - b) If we get back a stream error of which the source is a broken connection, we `waitUntilConnectionIsReady` and subsequently get a new stream from the server.

Even while a) might seem more robust I would prefer b) as this seems the right thing to do (the grpc way). Also I would have to check if we have a corresponding request for every subscription.


As this Issue might end in a major rework of the lnd plugin, this dependency might come in quite handy:
https://github.com/lightninglabs/lndclient
which is lnds client wrapper for `go` that might save us some repetitive work.

What are your thoughts on this suggestions?
