### ISSUE TITLE
make lnd-release does not install in GOPATH

### ISSUE THREAD

**Issue by yuyaogawa** [ElementsProject/peerswap#118]
The built files `peerswapd` and `pscli` are located in the peerswap root directory instead of under GOPATH/bin for `make lnd-release` command.

**Comment by wtogami** [comment]
Is this an expectation of all go apps?

Would it be OK to have separate build and install targets?

I think maybe `cln-release` we don't want to install into GOPATH/bin because it isn't run by users and CLN must run plugins by full pathname?

**Comment by yuyaogawa** [comment]
In the LND setup doc [here](https://github.com/ElementsProject/peerswap/blob/master/docs/setup_lnd.md), 

> This will install peerswapd and pscli to your go path

but these files are not installed to GOPATH, so I need to move them to GOPATH manually.

>Would it be OK to have separate build and install targets?

Do you mean we want to have another build command like `make lnd-install`?

**Comment by nepet** [comment]
@wtogami PR #119 only affects the `make lnd-release` command, not the `make cln-release`. There is no change in the workflow for cln.

**Comment by wtogami** [comment]
I know. Asking if we should do similar.

**Comment by yuyaogawa** [comment]
It depends, but I think changing build command from `go build` to `go install` for only lnd would be appropriate since `make lnd-release` is supposed to be command to install.

**Comment by yuyaogawa** [comment]
resolved by #119
