### ISSUE TITLE
Unable to swap out "Unknown desc = Fee is too damn high"

### ISSUE THREAD

**Issue by dannydeezy** [ElementsProject/peerswap#135]
I'm running latest master branch of peerswap (commit 55534113b57865a26af6cc86af54cce505f6684b)
along with LND v0.15.1-beta

I tried:
```
./pscli swapout --sat_amt 10000000 --channel_id 813154819615621120 --asset btc
```

But got error:
```
rpc error: code = Unknown desc = Fee is too damn high. Max expected: 0 Received 2112
```

Have never been able to swap, always get this error or similar

**Comment by nepet** [comment]
Can this be closed now?

**Comment by wtogami** [comment]
he was accidentally running an old version
