### ISSUE TITLE
"swaps_allowed" and "lbtc" reported despite incorrect

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#14]
```
$ lightning-cli peerswap-listpeers
   {
      "nodeid": "HIDDEN",
      "swaps_allowed": true,
      "supported_assets": [
         "lbtc",
         "btc"
      ],
```

It shouldn't say true here while this peer's pubkey isn't whitelisted.

version: 4a5ee00ae2657673073da42db37e311488a5a794

**Comment by wtogami** [comment]
"swaps_allowed" is also ambiguous. Is it meant to mean they allow swaps from you or you allow swaps from them?

**Comment by wtogami** [comment]
`lbtc` is listed as supported in `listpeers` even if that peer doesn't have a lbtc wallet.

Related bug?

**Comment by wtogami** [comment]
```
2022-06-01T12:59:59.318Z DEBUG   plugin-peerswap-plugin: [Messenger] From: REDACTEDPUBKEY got msgtype: a463 payload: {\"version\":0,\"assets\":[\"lbtc\",\"btc\"],\"peer_allowed\":true}
```

**Bug Confirmed** - All of the PeerSwap enabled peers are reporting `lbtc` despite some of them not having elementsd.

I have not confirmed what happens to `peer_allowed` if they haven't listed your pubkey.

**Comment by wtogami** [comment]
As of today I'm not sure this bug is still happening. One peer legit does not have lbtc. It correctly reports just btc.

@grubles have you seen this bug recently?

**Comment by grubles** [comment]
Just checked and some nodes report only BTC, so I suspect it's not happening for me at least.
