### ISSUE TITLE
"balance" is awkward in listpeers channels

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#16]
```
      "channels": [
         {
            "short_channel_id": "HIDDENxHIDDENx1",
            "local_balance": 948887,
            "remote_balance": 51113,
            "balance": 0.948887,
            "state": "CHANNELD_NORMAL"
         }
```

The word `balance` here feels wrong while the other two numbers are  `*_balance`. This number is more of a ratio or a fraction?

Any thoughts for a better word to use here?

**Comment by nepet** [comment]
I am on your page here. It is not a balance at all but more a ratio or portion. Question is, why do we need this field at all? One could just calculate it by themselves by dividing the `local_balance` by the sum of `remote_balance` and `local_balance`.
Any thoughts about dropping this field entirely?

**Comment by wtogami** [comment]
It could be related to a desired target channel ratio. For example many channels want to be 50% while others want to be mostly on one side or the other. I think keeping it is fine but I am really unsure what it should be called.

**Comment by sputn1ck** [comment]
> I am on your page here. It is not a balance at all but more a ratio or portion. Question is, why do we need this field at all? One could just calculate it by themselves by dividing the `local_balance` by the sum of `remote_balance` and `local_balance`.
> Any thoughts about dropping this field entirely?

I think that field is pretty valuable in the context of desired target channel ratio. I would personally like to call `swap-in` with a desired ratio e.g. 0.50 and then peerswap would determine the sats needed. 

I agree that `balance` is misleading. Also is `1.0` all balance on my side or on my peers side?

**Comment by wtogami** [comment]
Discussion: `localpercentage` might be the closest name to intended meaning. Anyone have a better idea?

**Comment by nepet** [comment]
sgtm!
