### ISSUE TITLE
Monitor auth cookies for changes and reload

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#17]
```
$ lightning-cli peerswap-lbtc-getbalance
{
   "code": -1,
   "message": "Authorization failed: Incorrect user or password"
}
```

If `bitcoind` or `elementsd` had restarted then their respective cookies would have changed. Please consider checking their file timestamp and if it had changed reload before running each RPC command?

**Comment by wtogami** [comment]
Can this be done cleanly with a minimal amount of code?

**Comment by nepet** [comment]
Let me check if I can easily add a wrapper around the rpc clients that intercepts all calls, or at least the ones we use.

**Comment by wtogami** [comment]
```
[lightning@server liquidv1]$ cat .cookie 
__cookie__:1a523cd9931b57ad26fcd2a4507c82a328cc4591e2b2ecb7690b8aba6ef4d54c
[lightning@server liquidv1]$ elements-cli stop
Elements Core stopping
[lightning@server liquidv1]$ elementsd
Elements Core starting
[lightning@server liquidv1]$ cat .cookie 
__cookie__:0ec559c2e881d2b95e93708cfde3fdbac13f92e79a029e05c29d85ce81665a72 
```

### How about this?
* Periodically check if `~/.bitcoin/cookie` and `~/.elements/liquidv1/.cookie` changed and reload. It's just reading the file so it could be very often like every minute. Silent if nothing changed.
* Any RPC failing with "Authorization failed" behaves like it does now (generally informing the client and remote peer of the error), but afterward throws PeerSwap back into `Waiting for cln to be synced...`
* In the case of single commands like `peerswap-lbtc-getbalance` nothing gets logged in the case of `Authorization failed: Incorrect user or password`. This could be logged.

The above handles only cookie mode after restarts. We need something slightly different for hard-coded rpcuser/rpcpassword for it to recognize the underlying daemon restarted and PeerSwap needs to wait.

**Comment by nepet** [comment]
Okay, so peerswap constructs the rpc-clients once at initialization. Peerswap uses a variety of rpc-clients and ways to access the underlying daemons. 
These are:
- cln/btc: 
  - `gbitcoin` for chain tx-watcher, fee-estimator and `sendrawtransaction`
  - `core-lightning` as a proxy for wallet stuff, mainly constructing and signing `psbts` except `sendrawtx`.
- cln/lbtc: `gelements`
- lnd/btc: `lnd` as a proxy for all requests, as we can not know if it uses btcd or bitcoind under the hood.
- lnd/lbtc: `gelements`

`gelements` as well as `gbitcoin` do not have a way to change the connection parameters at runtime. They just take the `user` `password` `host` `port` quadruple and store them, on every request they take the stored values to build the authentication header and the destination of the request.

What we could do is:
- Create a proxy for `gelements` and `glightning` that checks on the cookie every time they get called. We would have to wire-up all calls that we use with all requests and all responses. Also we need to decide if someone set the password/user in the config or set a cookie path or did use the default settings to decide what we should do and what intended/expected behavior is. This seems like a lot of work and potentially error prone to misinterpretation of the user configuration.

Is it known if core-lightning auto-reconnects on cookie change?

**Comment by wtogami** [comment]
> Create a proxy for gelements and glightning

The goal of a proxy is to attempt to not allow a RPC to fail.
My point is it already failed at this point and it should go back to initialization, the same as if peerswap were restarted. The normal wait for daemons to be ready and recovery should work no matter which state it previously failed?

>  Okay, so peerswap constructs the rpc-clients once at initialization.

Can we go back to the beginning, destroy those rpc-clients and initialize again without restarting the peerswap process?

**Comment by wtogami** [comment]
You're correct there are different scenarios.

* cookie file changed and Authorization failed - clearly the daemon restarted so peerswap needs to reload auth before retrying.
* explicit rpcuser and rpcpassword - it might come back if the underlying daemon is restarted but we don't have control of that, don't attempt to re-initialize, just retry forever

**Comment by wtogami** [comment]
> Is it known if core-lightning auto-reconnects on cookie change?

Confirmed it does auto-reconnect after a cookie change.

**Comment by nepet** [comment]
Re-initialization of the rpc-clients is really tricky as we would also have to recreate every single service that uses those rpc-clients. So even if bitcoind is perfectly fine we would need to restart the whole swap service (state machine, chain-watchers, wallets, on-chain-services, estimators) if elementsd changed cookies. This means we have to gracefully stop the whole service (only on the cookie-scenario, which we would also need to detect) read the cookie file again, initialize a new set of rpc-clients and start all services again which then need to recover sanely.
For this we would need to hand down a context to all services (which is go best practice anyhow), tell them to cancel their operations and return back to the setup step.
This seems like a huge effort and would require a lot of rework of the overall architecture. It would also require to rewrite the state machine to be able to handle a graceful stop in all cases (no external events from listeners, more cohesive states), which, to be honest, would not be a bad idea at all!.

We can unfortunately not just swap out the rpc-clients in-place as we have to deal with different implementations (lnd, cln) and therefore need to use interfaces to express shared behavior.

The easiest solution (still requires some work) for peerswap seems to be a proxy that does re-read the cookie file on every call IF a cookie file is set (which is default on empty config), or re-reads if we get a connection error.

**Comment by wtogami** [comment]
After the #215 flake is fixed we need to release.

The simplest thing we can add for the release is upon RPC authorization failure exit. That's better than looping forever while it can't possibly recover. Reapproach this post-release.

**Comment by YusukeShimizu** [comment]
> The easiest solution (still requires some work) for peerswap seems to be a proxy that does re-read the cookie file on every call IF a cookie file is set (which is default on empty config), or re-reads if we get a connection error.

This method seems to fail if bitcoind or elementsd restarts with a different cookie file path, correct?
I think this might need to make the cookie file path changeable in some way.

**Comment by wtogami** [comment]
I'm not concerned about the cases where there was an underlying configuration change. Restarting the plugin is easy and expected in that case.

This ticket is about restarting the underlying bitcoind and elementsd without configuration changes which you would expect to automatically recover.

**Comment by YusukeShimizu** [comment]
As a simple countermeasure, if no username or passphrase is set and there is a cookie file update, I have added the ability to retrieve it again from the cookie before making the request for gbitcoin/gelements.

https://github.com/ElementsProject/glightning/pull/10.

If there are no problems with this response, I will add an update to peerswap as well.

**Comment by wtogami** [comment]
If glightning learns how to read the cookie file again then parts of #219 need to be undone. Unfortunately a lot more work needs to be done on top of that.

If the underlying bitcoind or elementsd are restarted we unfortunately need to go back into a "wait for startup" state similar to #206. Otherwise things will break if you try the RPCs too soon after a daemon restart.

This might be a lot of work when it might be easier to restart peerswap? Is this a lot of work?

Otherwise it might be better to get working on higher priority features instead.
