### ISSUE TITLE
nix-shell failing on mac

### ISSUE THREAD

**Issue by JssDWt** [ElementsProject/peerswap#177]
When I invoke the command `nix-shell` on Mac (MacOS Ventura 13.2.1) I get compilation errors around some `API_AVAILABLE`/`API_UNAVAILABLE` code. Does this mean anything to you? I can't figure out which part is not working.

Output attached in file [nix-shell-output.txt](https://github.com/ElementsProject/peerswap/files/10931493/nix-shell-output.txt)

**Comment by nepet** [comment]
Was this introduced, merging #175?

**Comment by JssDWt** [comment]
> Was this introduced, merging #175?

I tried again with commit https://github.com/elementsproject/peerswap/commit/2e2177e947e220de73002df7bdcc8bd97dd354f7

Build does work there, so I guess it's introduced in that PR, yes.
Script ends with the following in this commit, but no error sprees.

```
found 0 vulnerabilities
linking bin 'mmdc'
patching script interpreter paths in /nix/store/nwi1k60928bvk19mq3v2iyqq24hwn1fw-_at_mermaid-js_slash_mermaid-cli-9.2.2/lib/node_modules/@mermaid-js/mermaid-cli/src/cli.js
installPhase completed in 44 seconds
post-installation fixup
rewriting symlink /nix/store/nwi1k60928bvk19mq3v2iyqq24hwn1fw-_at_mermaid-js_slash_mermaid-cli-9.2.2/bin to be relative to /nix/store/nwi1k60928bvk19mq3v2iyqq24hwn1fw-_at_mermaid-js_slash_mermaid-cli-9.2.2
patching script interpreter paths in /nix/store/nwi1k60928bvk19mq3v2iyqq24hwn1fw-_at_mermaid-js_slash_mermaid-cli-9.2.2
bash: ./contrib/startup_regtest.sh: line 50: syntax error near unexpected token `else'
bash: ./contrib/startup_regtest.sh: line 50: `    else'
bash: setup_alias: command not found
```

**Comment by nepet** [comment]
Sorry for the late response, I got trapped in a nixpkg rabbit hole. It seems that the bitcoin v24.0.1 nix package fails to build on darwin (at least x86_64). #178 reverts to v24.0 which seems to work for me.

Could you give it a try and report if the PR also works for you (besides the `dup3` issue)

**Comment by JssDWt** [comment]
> Could you give it a try and report if the PR also works for you

Works for me!
