### ISSUE TITLE
flake: TestPeerListener_Reconnect_OnGracefulStop

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#222]
I think this is one of the possible flakes after #215 was merged.

https://github.com/ElementsProject/peerswap/actions/runs/5920946834/job/16052868144
```
=== CONT  TestPeerListener_Reconnect_OnGracefulStop
    peerlistener_test.go:174: Failed Connect(): ConnectPeer() rpc error: code = Unknown desc = server is still in the process of starting
2023/08/21 01:53:24 [DEBUG] [grpc_conn]: grpc_retry parent context error: context canceled
2023/08/21 01:53:24 [INFO] [PeerListener]: Stream closed by client: context canceled
=== CONT  TestPeerListener
--- FAIL: TestPeerListener_Reconnect_OnGracefulStop (18.18s)
```

**Comment by wtogami** [comment]
https://github.com/ElementsProject/peerswap/actions/runs/5920946834/job/16053541420
subsequent test run passed

**Comment by nepet** [comment]
The flake here is produced by an LND test and should not be related to #215. This seems more related to lnd introducing a new error message `server is still in the process of starting` next to the other 3 rpc errors with code `unknown` and different error messages that tell us that lnd is still starting up.

I am going to add the new message to `retry-middlewar` we added some time ago to the lnd connection.
