### ISSUE TITLE
plugin crashes after update to Core Lightning v23.08

### ISSUE THREAD

**Issue by sat-hoarder** [ElementsProject/peerswap#224]
Plugin will load on initial startup and crash on first lightning-cli call.  Panic-log:

Server started 2023-08-24T03:52:49Z
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
github.com/elementsproject/peerswap/clightning.BitcoinFallbackFromClnConfig.func1(0xc0004b4a00)
        /root/peerswap/clightning/config.go:274 +0x46d
github.com/elementsproject/peerswap/clightning.(*Pipeline).Run(0xc0002a5af0)
        /root/peerswap/clightning/config.go:450 +0xde
github.com/elementsproject/peerswap/clightning.GetConfig(0xc0003fe000)
        /root/peerswap/clightning/config.go:432 +0x69b
main.run({0x103fcd8?, 0xc0001a6eb0}, 0xc0003fe000)
        /root/peerswap/cmd/peerswap-plugin/main.go:130 +0x208
main.outer()
        /root/peerswap/cmd/peerswap-plugin/main.go:101 +0x1e5
main.main()
        /root/peerswap/cmd/peerswap-plugin/main.go:55 +0x137

**Comment by wtogami** [comment]
What version of peerswap? We've been heavily using recent and current master branch. It's close to release candidate.

**Comment by sat-hoarder** [comment]
cloned a fresh master and compiled with go 1.20

**Comment by grubles** [comment]
Do you have `allow-deprecated-apis=false` set in your CLN config?

**Comment by sat-hoarder** [comment]
I have **allow-deprecated-apis=true** set in my config

**Comment by grubles** [comment]
`interface {} is float64, not string` 

Do you have `bitcoin-rpcport` set in your CLN config? If so can you paste the line for us? It appears CLN is providing PeerSwap with the wrong type (float64 instead of string).

**Comment by sat-hoarder** [comment]
It was only logging INFO events.  I commented out just the bitcoin-rpcport and now peerswap loads and doesn't die.  I'm happy to post the INFO lines if you'd like

**Comment by grubles** [comment]
Ok I reproduced where the plugin is killed after trying to start but not the original panic yet. I suspect the problem might be because CLN 23.08 changed the `listconfigs` API to return a `configs` subobject instead of a dict. https://github.com/ElementsProject/lightning/pull/6243
