### ISSUE TITLE
PeerSwap doesn't start if using CLN 23.08 and if bitcoin-rpcport is set in CLN config

### ISSUE THREAD

**Issue by grubles** [ElementsProject/peerswap#225]
When running CLN 23.08, if `bitcoin-rpcport` is set in the CLN config, PeerSwap fails to start: 

```
2023-08-24T14:49:01.937Z INFO    plugin-peerswap: PeerSwap starting up with commit 19eeea491fe39cad78302096b6b2bd922af61be8
2023-08-24T14:49:01.937Z INFO    plugin-peerswap: DB version: v0.2, Protocol version: 3
2023-08-24T14:49:01.937Z INFO    plugin-peerswap: Using data dir: /home/user/.lightning/signet
2023-08-24T14:49:01.941Z INFO    plugin-peerswap: Killing plugin: exited during normal operation
```

Commenting `bitcoin-rpcport` out fixes it and PeerSwap is able to start. 

CLN 23.08 introduced a change to `listconfigs`. Could this be the root cause?

**Comment by grubles** [comment]
So the error in #224 alludes to `bitcoin-rpcport` being converted into a `float64` at some point (glightning?). If I convert it to `uint` , PeerSwap is able to start up:

```go
if v, ok := plugin.Options["bitcoin-rpcport"]; ok {
						if v != nil {
							c.Bitcoin.RpcPort = uint(v.(float64))
						}
					}
```

https://github.com/ElementsProject/peerswap/blob/master/clightning/config.go#L272

**Comment by grubles** [comment]
Turns out go unmarshals JSON numbers into `float64` by default: https://pkg.go.dev/encoding/json#Unmarshal

**Comment by nepet** [comment]
> ... being converted into a `float64` at some point (glightning?) ...
> ...
> Turns out go unmarshals JSON numbers into float64 by default: https://pkg.go.dev/encoding/json#Unmarshal

The reason for that is that javascript only knows a single primitive `number` type that is basically a float64.
