### ISSUE TITLE
we should warn if CLN users set allow-deprecated-apis=false

### ISSUE THREAD

**Issue by grubles** [ElementsProject/peerswap#228]
CLN will deprecate parts of its API and these changes will have the potential to negatively affect the function of PeerSwap. The CLN team gives developers and users some time before fully removing the deprecated parts, and include a config option `allow-deprecated-apis=bool` to toggle the deprecated API parts on and off for testing purposes. 

We should detect the config option and print a warning.

**Comment by nepet** [comment]
:+1:
