### ISSUE TITLE
PeerSwap creates unblinded addresses with Elements v23

### ISSUE THREAD

**Issue by grubles** [ElementsProject/peerswap#256]
During a swap, PeerSwap will try to create what it expects to be a CT address using Elements. But in the next Elements release (v23) the `generatenewaddress` RPC is [changed](https://github.com/ElementsProject/elements/pull/1246) to create non-CT bech32 addresses. Because PeerSwap (or go-elements?) is expecting a CT address, an error occurs during a swap: 

```
"cancel_message": "failed to generate surjection proof, please retry"
```

It seems we need to modify PeerSwap (or go-elements?) to create blech32 addresses explicitly now?

**Comment by delta1** [comment]
https://github.com/ElementsProject/glightning/blob/master/gelements/elementsd.go#L354 

looks like you’ll need to add Blech32 to this enum, and then update the call site to use the correct int here 

https://github.com/ElementsProject/peerswap/blob/c22211a9ea6aad15af32266901d620afd1ad2c5f/wallet/elementsrpcwallet.go#L127

**Comment by delta1** [comment]
this string impl will also need “blech32” 

https://github.com/ElementsProject/glightning/blob/master/gelements/elementsd.go#L359

**Comment by grubles** [comment]
@sat-hoarder We have a patch you can use. https://github.com/ElementsProject/peerswap/pull/257
