### ISSUE TITLE
Latest CLN defaults to wumbo now. PeerSwap's wumbo / large-channels check is broken. 

### ISSUE THREAD

**Issue by grubles** [ElementsProject/peerswap#261]
```
$ lightning-cli --signet peerswap-swap-out 140490x1x0 246942696 lbtc                                                                                      
{
   "code": -1,
   "message": "swap amount is 246942696000: need to enable option '--large-channels' to swap amounts larger than 2^32 msat"
}
```

```
$ cat ~/.lightning/config
signet
plugin=/home/user/.lightning/signet/plugins/peerswap
daemon
log-file=logs
log-level=debug
```

`large-channels` is missing, so PeerSwap considers it turned off and won't allow the swap to continue past that check. 

Even adding `large-channels` to the CLN config does not help.

Commenting this line out allows the swap to continue: https://github.com/ElementsProject/peerswap/blob/c22211a9ea6aad15af32266901d620afd1ad2c5f/clightning/clightning.go#L187

**Comment by nepet** [comment]
My PR to upgrade cln on nix go merged https://github.com/NixOS/nixpkgs/pull/270897 . We can upgrade the tests now to find out what else is broken.
Note: the `--enable-developer` flag got retired so there are no developer builds anymore. Developer features are enabled by the the `--developer` runtime option. We need to update the tests to do so.
