### ISSUE TITLE
Kind of typo/format error in logs

### ISSUE THREAD

**Issue by zx9r** [ElementsProject/peerswap#276]
Not an important bug but just letting you know just in case:

> 2024/01/22 14:38:24 [INFO] Elementsd still syncing, progress: %!d(float64=0.999)
> 2024/01/22 14:38:34 [INFO] Elementsd still syncing, progress: %!d(float64=0.999)
> 2024/01/22 14:38:54 [INFO] Elementsd still syncing, progress: %!d(float64=0.999)

**Comment by grubles** [comment]
Good eye! Thanks for the report.

**Comment by grubles** [comment]
I think we just need to change the `%d` to `%f` since `gelements` is returning a float.

**Comment by grubles** [comment]
Yep that did the trick. 

```
2024/01/25 18:04:12 [INFO] Bitcoin swaps enabled on network signet
2024/01/25 18:04:12 [INFO] Liquid swaps enabled
2024/01/25 18:04:12 [INFO] Elementsd still syncing, progress: 0.015000
2024/01/25 18:04:22 [INFO] Elementsd still syncing, progress: 0.021000
2024/01/25 18:04:42 [INFO] Elementsd still syncing, progress: 0.033000
2024/01/25 18:05:22 [INFO] Elementsd still syncing, progress: 0.059000
```
