### ISSUE TITLE
`peerswap-listpeers` missing `channels` field due to CLN API removal

### ISSUE THREAD

**Issue by grubles** [ElementsProject/peerswap#299]
CLN v24.05 [removed](https://github.com/ElementsProject/lightning/blob/master/CHANGELOG.md#removed) the `channels` field from `listpeers`. This means the `peerswap-listpeers` command is also now missing that field. Reported by @Impa10r on Discord. 

How difficult will it be to use CLN's `listpeerchannels` instead?

Related to #194.

**Comment by Impa10r** [comment]
> CLN v24.05 [removed](https://github.com/ElementsProject/lightning/blob/master/CHANGELOG.md#removed) the `channels` field from `listpeers`. This means the `peerswap-listpeers` command is also now missing that field. Reported by @Impa10r on Discord.
> 
> How difficult will it be to use CLN's `listpeerchannels` instead?
> 
> Related to #194.

Would need to add that method here first:
https://github.com/ElementsProject/glightning/blob/55240d61b52a059ece7d3eca0ed05fe3c413ee54/glightning/lightning.go#L2583
