### ISSUE TITLE
Failed to claim funds after swap, state shows "State_ClaimedCoop" but funds are still unclaimed

### ISSUE THREAD

**Issue by cienegajal** [ElementsProject/peerswap#339]
How I got here:

Running elements 23.2.4, peerswap-web v1.7.4 with lnd v0.18.0-beta

I made an error while editing my docker file manually and it seems like "creatediscountct=1" got ignored from elements config:

![Captura de pantalla 2024-12-27 140235](https://github.com/user-attachments/assets/80989f39-9b70-4e08-9701-3f411ba81095)

elements output:
...
_2024-12-27T18:01:09Z Command-line arg: peerblockfilters="1 -creatediscountct=1"_
...

while I was trying a swap-out (ln to liquid) with a peer I got this error:

...
_2024/12/27 15:58:09 [INFO] Error claiming tx with preimage MinRelayFee not met
2024/12/27 15:58:13 [INFO] Error claiming tx with preimage MinRelayFee not met
2024/12/27 15:58:23 [INFO] Error claiming tx with preimage MinRelayFee not met
2024/12/27 15:58:31 [INFO] [MsgListener]: Handler failed: Message already exists
2024/12/27 16:03:59 [INFO] [Swap:e571e81999de409a9b3a8aa069ca64699895ae4ba1b0de69cbc13891eba82baf] Swap claimed cooperatively_
...

This made me think that maybe the claiming tx was not broadcasted due the low fee considered by the discount not being expected by elements.

explored a bit using boltbrowser and at the bottom of the swap json I see this:

...
_"type": 2,
  "role": 1,
  "previous": "State_SwapOutSender_SendCoopClose",
  "current": "State_ClaimedCoop"}_
...

There is a "opening_tx_hex" that matches the one confirmed on liquid, but the _"claim_tx_id": ""_, appears empty

In the liquid explorer the outputs of the swap appear as unspent, and in the swap entry in the swaps db I see the "claim_payment_hash": "*******", and "claim_preimage": "*****"

Is there a way to safely claim the funds?

**Comment by Impa10r** [comment]
@grubles the swap-out peer got the lightning funds and considers the swap complete. is it possible to roll back the swap state to claim liquid again?

**Comment by Impa10r** [comment]
@cienegajal yes, stop peerswapd, backup swaps file, edit the state to State_SwapOutSender_ClaimSwap with boltbrowser, start peerswapd. it started clailing again in my testnet setup

**Comment by cienegajal** [comment]
thanks! that did the trick!, 

changed the "current" key from "State_ClaimedCoop" to "State_SwapOutSender_ClaimSwap" and now peerswap claimed the pending output

**Comment by cienegajal** [comment]
thanks! that did the trick!, 

changed the "current" key from "State_ClaimedCoop" to "State_SwapOutSender_ClaimSwap" and now peerswap claimed the pending output
