### ISSUE TITLE
Too many reconnects if lnd is unavailable

### ISSUE THREAD

**Issue by rkfg** [ElementsProject/peerswap#57]
If lnd restarts for any reason peerswapd tries to reconnect as fast as it can which results in enormous amounts of logs and CPU load for no reason. These attempts should happen at least once in 5-10 seconds.

**Comment by wtogami** [comment]
@rkfg please test #66 with your LND and report back.

**Comment by wtogami** [comment]
Just checking to be sure, you're running #66, not master branch?

**Comment by wtogami** [comment]
@nepet said he will look specifically at reconnect handling.

**Comment by nepet** [comment]
Is resolved by #117
