### ISSUE TITLE
[CLN] improve invoice memo

### ISSUE THREAD

**Issue by sputn1ck** [ElementsProject/peerswap#58]
https://github.com/ElementsProject/peerswap/blob/9fb06e17f9bc79f4032c0b4aa9b92c97bb1c1eec/clightning/clightning.go#L250

Print 
- swap-in
- type of swap (swap-in/out)
- asset of swap
- type of invoice (fee/preimbursement/swap)

**Comment by wtogami** [comment]
`swap-out <ID>`
`swap-out fee <ID>`
`swap-out preimbursement <ID>`
I like this word but maybe it's too long. Either word is fine.

**Comment by nepet** [comment]
How about:
`<swap-type> <asset> <invoice-type> <ID>`
