### ISSUE TITLE
Change `peerswap-plugin` binary name to `peerswapcln`

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#72]
It was originally named `peerswap` but later renamed to the current `peerswap-plugin`.

```
2022-06-03T00:49:43.585Z INFO    plugin-peerswap-plugin: [Swap:fe679c6cce34905c15e31db98a1242c8dee0d31b66997c18c4a3f84a3371447c] Paid Feeinvoice of 258 sats
```

It looks stupid in logs. I don't want to look at the redundant word in logs for years. We're changing this back before the release of v0.3.0.

My bad.

**Comment by wtogami** [comment]
It was renamed from `peerswap` to `peerswap-plugin` because I thought the name looked ambiguous, one character different from the LND `peerswapd` binary.

How about `peerswapcln` for the plugin binary name? Shorter, not redundant in CLN logs, and not ambiguous as to what it is.

**Comment by openoms** [comment]
Naming is hard, but I agree to change the plugin name to `peerswapcln` - already using that as the config option in raspiblitz https://github.com/rootzoll/raspiblitz/pull/3202.

I think it would make the naming even more consistent if the `peerswapd` binary for LND would be called `peerswaplnd` avoiding the confusion that it might cause if someone thinks it is needed for CLN also. 
I like `pscli` as it is short and is somewhat a self-explanatory as a pair of the `peerswapd` / `peerswaplnd` daemon.

**Comment by wtogami** [comment]
Thank you for expressing opinions!

Yeah I like the idea of renaming the LND binary as well.
