### ISSUE TITLE
Make wumbo mandatory

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/peerswap#80]
related: #78 

We want to eliminate other scenarios that we didn't test for. Target users of PeerSwap really need larger channels. There is no good reason to operate a non-wumbo LN node with peerswap. PeerSwap should check for this during startup and refuse to load if the accompanying LN node is not properly configured then print an informative error message before exiting.

CLN has `listconfigs` which can show configuration options.
LND has something similar?

**Comment by openoms** [comment]
Not sure if forcing large channels is necessary.
Smaller nodes could still use and benefit from PeerSwap and maybe would not be comfortable receiving/opening such channels. It might not look extreme now, but keep in mind a 10x purchasing power.

Also don't know a way to check in LND apart from parsing the `lnd.conf`.

**Comment by wtogami** [comment]
> Not sure if forcing large channels is necessary.
The main reason for wumbo is it reduces the scenarios we need to test for. We can't afford unexpected behavior in a configuration that we did not test much at all.

Also note: CLN v0.12 they are considering making wumbo default.

**Comment by sputn1ck** [comment]
https://github.com/lightning/bolts/blob/master/09-features.md

specifies featurebit 18/19 as wumbo channels. On startup we could run `lncli getinfo` and restrict swaps larger than 4.2mm sats to only wumbo enabled nodes.

**Comment by sputn1ck** [comment]
> Does this really mean that PeerSwap is not expected to work with smaller than 16M channels?
> 

IIUC it is not about the channelsize, but the way payments larger than 4.2m sats are paid / simply if the festurebit is set. As in we can more easily support wumbo-enabled channels of less than 16m sats than non-wumbo enabled channels.

**Comment by wtogami** [comment]
> Does this really mean that PeerSwap is not expected to work with smaller than 16M channels?

I'm pretty sure wumbo enabled channels below 16 million sats are able to transfer the entire amount without MPP?

**Comment by openoms** [comment]
There is nothing I found in the specs thats suggests that the wumbo setting affects the max HTLC size:
https://github.com/lightning/bolts/blob/master/02-peer-protocol.md
> 
>The option_support_large_channel is a feature used to let everyone know this node will accept funding_satoshis greater than or equal to 2^24. Since it's broadcast in the node_announcement message other nodes can use it to identify peers willing to accept large channel even before exchanging the init message with them.

>The requirement for funding_satoshis to be less than 2^24 satoshi was a temporary self-imposed limit while implementations were not yet considered stable, it can be lifted by advertising option_support_large_channel.

https://amboss.space displays the max HTLC-s of nodes and it showed the number equal to the size of the channel for a node I know not has wumbo configured.

**Comment by wtogami** [comment]
What benefit is there in running with non-wumbo, and is that worth ballooning the quantity of required test cases to ensure it doesn't break here?

**Comment by openoms** [comment]
> What benefit is there in running with non-wumbo, and is that worth ballooning the quantity of required test cases to ensure it doesn't break here?

I see it as a default protection for having and moving large amounts on the node, but agree that it does not worth risking to break the larger swaps.
Will just add the option to the config files in the PeerSwap install script.
As it will be set manually by most it would be best to start recommending already in the installation notes.

**Comment by wtogami** [comment]
CLN v0.12 they're considerig making wumbo default.

This ticket would make PeerSwap refuse to start if wumbo is not active so users won't make mistakes.
