### ISSUE TITLE
Use feature flag to announce Peerswap

### ISSUE THREAD

**Issue by nepet** [ElementsProject/peerswap#82]
We might want to use a https://github.com/lightning/bolts/blob/master/09-features.md feature flag to announce that peerswap is enabled on a node.

**Comment by remyers** [comment]
Removing the current workaround would be very helpful for integration testing with Eclair.

Perhaps in the short term, could you just add a way to disable the polling messages check? Otherwise we will need to either implement the MESSAGETYPE_POLL and MESSAGETYPE_REQUEST_POLL ourselves, or more likely use a local fork that disables the test.

**Comment by remyers** [comment]
An important question is whether or not PeerSwap should be added to the BOLTs or be designed to work without changes to the BOLTs. 

If it will be an optional feature described in the BOLTs, then we should follow the lead of  [option_will_fund: liquidity ads #878](https://github.com/lightning/bolts/pull/878) and propose a new TLV for the  `node_ann_tlvs` field of `node_announcement` such as  `option_will_peerswap`.

The new TLV could include the information currently included in the [POLL message](https://github.com/ElementsProject/peerswap/blob/b1041aca6a81a5854c025e2587aa0486efebef4e/poll/messages.go#L6): 
* PeerSwap version
* Supported asset type(s). 

The new TLV could also include the requirements a node has to allow another node to be a peer swap partner. What these requirements are is an open question that requires more feedback from users. This would just be informational and can't be enforced, so it might not be useful to announce. Someone who peers with your node should do it for other reasons than to peer swap.

This announcement could also include details about the specific roles a node will participate in. For example, an online shop could advertise that they will only act as a `swap-in taker` and `swap-out maker`. Again, this is only informational and can't be enforced.

That said, if Peerswap nodes should connect to each other for reasons other than their willingness to do swaps, then it will not require changes to the BOLTs. Instead we can add the POLL messages to the Peerswap spec.

**Comment by nepet** [comment]
For further discussion check out https://github.com/ElementsProject/peerswap-spec/issues/5
