### ISSUE TITLE
Message cue for abandoned peers

### ISSUE THREAD

**Issue by nepet** [ElementsProject/peerswap#84]
Sometimes a peer might go missing. In the case of sending a cancel message to the peer we could keep a message queue that resends the latest message, the first that could not be delivered on disconnect, as soon as the peer reconnects. The peer could either ask for the latest message or the node could watch on connected peers and continue as soon as the peer reconnects.

Currently we just fail the cancel action such that it is not possible to recover a coop case. In this case the peer must wait for the csv limit to pass.

**Comment by wtogami** [comment]
Message queue might need deduplication as well?

**Comment by nepet** [comment]
This seems too sophisticated for the moment. I will close the issue and we could come back to it in the future
