### ISSUE TITLE
peerswap-plugin compile error on aarch64

### ISSUE THREAD

**Issue by openoms** [ElementsProject/peerswap#89]
Testing on aarch64 Debian (RaspiBlitz v1.8.0rc3)
```
₿ uname -a
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT aarch64 GNU/Linux

₿ go version
go version go1.17.3 linux/arm64
```
Running:
```
PATH=/usr/local/go/bin/:$PATH
make cln-release
```
```
go build -o peerswap-plugin -ldflags "-X main.GitCommit=e9d5a565e063208bf88ecea0af04aa48e75e15ce" ./cmd/peerswap-plugin/main.go
go: downloading github.com/btcsuite/btcd v0.22.0-beta.0.20211005184431-e3449998be39
go: downloading github.com/elementsproject/glightning v0.0.0-20220502095901-74f998c51367
go: downloading github.com/vulpemventures/go-elements v0.3.7
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading github.com/btcsuite/btcutil v1.0.3-0.20210527170813-e2ba6805a890
go: downloading github.com/btcsuite/btcutil/psbt v1.0.3-0.20210527170813-e2ba6805a890
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading golang.org/x/sys v0.0.0-20210915083310-ed5796bab164
go: downloading github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f
go: downloading golang.org/x/crypto v0.0.0-20211117183948-ae814b36b871
go: downloading github.com/vulpemventures/go-secp256k1-zkp v1.1.5
go: downloading github.com/vulpemventures/fastsha256 v0.0.0-20160815193821-637e65642941
# command-line-arguments
cmd/peerswap-plugin/main.go:627:8: undefined: syscall.Dup2
make: *** [Makefile:62: cln-release] Error 2
```

It is working on amd64 using the same scripts and software versions.

Edit: 
see the issue in go: https://github.com/golang/go/issues/10235
and a fix in another project: https://github.com/sevlyar/go-daemon/commit/2f19e76436a8afbb39ef64629d543cf07cddc7a5
more: https://stackoverflow.com/questions/55785908/how-to-use-os-or-arch-specific-code-in-go

**Comment by nepet** [comment]
Seems more like `Dup2` is not available which we use to copy the golang panics to a separate log file

**Comment by wtogami** [comment]
"Linux on aarch64 does not implement older syscalls such as open, fork and dup2."

https://github.com/ngaut/log/pull/5
Other go projects are fixing this by switching to dup3. But then there is a complaint from 2017 that it broke OSX. So we have anyone who can try this build on OSX?

**Comment by nepet** [comment]
I can test this and if OSX complains about dup3 we can OS guard this to use dup2 on OSX. IMHO OSX might be the least used os for peerswap right now, so I would suggest to focus on aarch64 for now

**Comment by wtogami** [comment]
I'll get someone to build test dup3 on OSX.
Shahana to my surprise has PeerSwap working on native Windows so should be tested there too.

**Comment by nepet** [comment]
This should only affect the cln plug-in.

**Comment by wtogami** [comment]
OSX fails to build for unrelated reasons and peter has a good point that this part of PeerSwap isn't usable for Windows.

So let's confirm dup3 on x86_64 and aarch64 Linux for now.

**Comment by swissrouting** [comment]
I can confirm that switching `Dup2` to `Dup3` was the only thing needed to make peerswap compile and run for me on aarch64.

```
-       err = syscall.Dup2(int(panicLogFile.Fd()), int(os.Stderr.Fd()))
+       err = syscall.Dup3(int(panicLogFile.Fd()), int(os.Stderr.Fd()), 0)
```
