### ISSUE TITLE
CLN: `msatoshi` in `sendpay` route got deprecated

### ISSUE THREAD

**Issue by nepet** [ElementsProject/peerswap#92]
ElementsProject/lightning@08d5776ebc3646ba924466be95416076a7852300 deprecates the msatoshi field which currently leads to jsonrpc errors. 

We have to remove the duplicate field in the route hints. One have to check on backwards compatibility as one of the fields was optional before.

**Comment by nepet** [comment]
ElementsProject/lightning#5306 seems to lack backwards compatibility and is discussed in ElementsProject/lightning#5386.

**Comment by wtogami** [comment]
This was fixed recently in CLN master branch.
