### ISSUE TITLE
"addpeer" command works with blank string

### ISSUE THREAD

**Issue by swissrouting** [ElementsProject/peerswap#93]
Example with CLN:

```
$ lightning-cli peerswap-addpeer
{
   "ReserveOnchainMsat": 0,
   "PeerAllowlist": [
      ""
   ],
   "AcceptAllPeers": false
}
```

Expected result: should see an error message like "peerswap-addpeer: missing argument for peer public key"

Actual result: successfully added an empty string to the PeerAllowlist.

**Comment by wtogami** [comment]
Good First Issue for someone who wants to get involved.

Suggested Fix:

- Validate the input is 66 characters, hex, lowercase.

Don't bother to deal with invalid line entries. People can delete them manually from their `policy.conf`.
